# MUST EDIT BELOW
sitename: TopTopic?             #Your site title
tagline: just another blog      #You should always have a tagline
url: http://blog.prskavec.eu    #URL Please
ga: UA-79221-49                 #Google Analytics ID
sitemap: GOOGLEWEBMASTER        #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    true
markdown:    maruku
permalink:   pretty
# END
exclude: LICENSE, README.markdown, Rakefile
